spring.application.name=order-service
spring.datasource.url=jdbc:postgresql://localhost:5434/orderDB
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update