CREATE TABLE IF NOT EXISTS shedlock(
    name VARCHAR(64),
    lock_until TIMESTAMP(3) NOT NULL,
    locked_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    locked_by VARCHAR(255),
    PRIMARY KEY (name)
);
