package com.pizzeria.internship.order_service.admin;

import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;

@Schema(description = "Performance metrics of a single location")
public record LocationMetrics(
        @Schema(description = "Identifier of the location", example = "1")
        Long locationId,

        @Schema(description = "Name of the city where the location operates", example = "Krakow")
        String cityName,

        @Schema(description = "Total revenue generated by the location in the range", example = "8210.75")
        BigDecimal totalRevenue,

        @Schema(description = "Total number of orders handled by the location in the range", example = "168")
        long orderCount,

        @Schema(description = "Average time between order creation and delivery, in minutes", example = "34.5")
        double fulfillmentTimeMinutes
) {}
