package com.pizzeria.internship.order_service.admin;

import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;

@Schema(description = "Ranking position of a single product")
public record ProductRankingItem(
        @Schema(description = "Identifier of the product in the catalog-service", example = "1")
        Long productId,

        @Schema(description = "Product name", example = "Margherita")
        String historicalName,

        @Schema(description = "Total quantity sold in the range", example = "214")
        long totalQuantity,

        @Schema(description = "Total revenue generated by the product in the range", example = "5350.00")
        BigDecimal totalRevenue,

        @Schema(description = "Share of the total revenue, expressed as a percentage", example = "35.12")
        double percentageOfTotal
) {}
